### ISSUE TITLE
Update pinned dependency

### ISSUE THREAD

**Issue by mbarkhau** [frnmst/fpyutils#3]
From the `md-toc` dependency I get your library as a dependency, which conflicts with a dependency of various pytest packages and get this error.

```
ERROR: fpyutils 1.1.0 has requirement atomicwrites==1.3.0, but you'll have atomicwrites 1.4.0 which is incompatible.
```

Could you update your requirement to `atomicwrites>=1.3`.

**Comment by frnmst** [comment]
Thanks.

I have updated this library. md-toc will be updated soon.
